[package]
name = "corpus-database"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.1"
serde_derive = "1.0.1"
serde_json = "1.0.0"
failure = "0.1.5"
bincode = "1.1.4"

[build-dependencies]
corpus-database-dsl = { path = "../database-dsl" }
